### PR TITLE
Convert to polymer 3

### LINKED ISSUE #7: Migrate to Polymer 3
Hello !

We use it our component since 2016 (thx) and we want migrate to Polymer 3.

Did you plan to migrate on it?
Would you accept a PR from me about this?

### PR DESCRIPTION
**Pull request by srijken**
Fixes #7

### CODE REVIEW

**Comment by srijken** [comment]
I sort of fixed the test run, only problem is that Chrome keeps crashing. This works fine locally. Ideas welcome.

**Comment by ankon** [comment]
> I sort of fixed the test run, only problem is that Chrome keeps crashing.

We discussed this a while ago in the context of other components here, and the outcome for both @ronnyroeller and me is that trying to keep the tests running is more effort than it is worth. web-component-tester is a mess, selenium is a mess, and the glue needed to keep this somehow alive changes every few weeks with either firefox or chrome being "good". 

I'd be fine with just dropping the tests completely.

**Comment by srijken** [comment]
@ankon Well it works for now.. so maybe just keep them until it fails again?

**Comment by ronnyroeller** [comment]
Closed as obsolete.
Many thanks for your input @srijken !

**Pull request closed without merging**
